name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    strategy:
      matrix:
        nodes: ["10.0.2.74", "10.0.2.75"]

    steps:
      - name: Deploy to ${{ matrix.nodes }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_HOST: ${{ matrix.nodes }}
        run: |
          echo "$SSH_PRIVATE_KEY" > keypair.pem
          chmod 600  keypair.pem
          ssh -o StrictHostKeyChecking=no -i keypair.pem $SSH_USERNAME@${{ matrix.nodes }} "
          cd /capstone-flask && 
          sudo docker pull rawanalanazi/capstone-projectt:latest &&
          sudo docker stop web || true && 
          sudo docker rm web || true && 
          sudo docker run -d -p 80:5000 --name web \
          --env-file .env \
          rawanalanazi/capstone-projectt:latest \"
